# Generated by Django 4.0 on 2022-01-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='LastName',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
